# 1. Scalars, Vectors, Matrices, and Tensors


Scalar: A scalar is a single real or complex number, often denoted as lowercase letters like a,b,or c.In machine learning, scalars often represent individual features or results of computations.

Vector: A vector is a 1-dimensional array of numbers, represented in column form. Vectors are commonly denoted by lowercase bold letters, e.g., v. Vectors are useful in representing data points or feature sets.

Matrix: A matrix is a 2-dimensional array of numbers organized in rows and columns, typically represented by uppercase bold letters, e.g., A. Matrices represent data, transformations, and relationships in machine learning.

Tensor: A tensor is a generalization of scalars, vectors, and matrices to multiple dimensions. For example, an image could be represented as a 3D tensor (width, height, color channels).

In [3]:
import numpy as np

#Scalar
scalar = 5
print('Scalar:',scalar)

#vector
vector = np.array([1,2,3])
print('Vector:',vector)

#Matrix
matrix = np.array([[1,2],[67,98]])
print("Matrix:",matrix)

# Tensor (e.g., a 3D tensor with shape (2, 2, 3))
tensor = np.array([
    [[1,2,3],[13,14,15]],
    [[4,5,6],[17,18,19]]
])
print("Tensor:",tensor)

Scalar: 5
Vector: [1 2 3]
Matrix: [[ 1  2]
 [67 98]]
Tensor: [[[ 1  2  3]
  [13 14 15]]

 [[ 4  5  6]
  [17 18 19]]]


# 2. Types of Matrices


Square Matrix: A matrix with the same number of rows and columns.

Diagonal Matrix: A square matrix where all elements except those on the main diagonal are zero.

Identity Matrix: A diagonal matrix with ones on the main diagonal and zeros elsewhere. It’s often denoted as I.

Symmetric Matrix: A square matrix that is equal to its transpose, i.e., 𝐴=𝐴^𝑇.

In [6]:
# Square Matrix
square_matrix =np.array([[1,2],[3,4]])
print("Square Matrix:",square_matrix)

#Diagonal Matrixx
diagonal_matrix=np.diag([5,8])
print("Diagonal MAtrix:",diagonal_matrix)

#Identity Matrix(2x2)
identity_matrix = np.eye(2)
print("Identity Matrix:",identity_matrix)

#Symmetric Matrix
symmetric_matrix = np.array([[2,3],[3,2]])
print("Symmetric Matrix:",symmetric_matrix)

Square Matrix: [[1 2]
 [3 4]]
Diagonal MAtrix: [[5 0]
 [0 8]]
Identity Matrix: [[1. 0.]
 [0. 1.]]
Symmetric Matrix: [[2 3]
 [3 2]]


# 3. Matrix and Vector Notations

Vectors : are usually denoted in lowercase bold letters like v, and each element within a vector can be accessed by vi.

Matrices : are typically represented in uppercase bold letters, such as A, and elements are accessed with two indices, Ai,j.



In [11]:
# Vector notation (1D array)
vector_notation = np.array([5,-1,3])
print("Vector Notation v:\n",vector_notation)
print('Type:',type(vector_notation))
print('Vector Size:',vector_notation.size)
print('Vector Shape:',vector_notation.shape)
print("Accessing Element v[1]:",vector_notation[1])

# Matrix notation (2D array)
matrix_notation = np.array([[45,65],[22,33]])
print("\nMarix Notaion:",matrix_notation)
print('Type:',type(matrix_notation))
print('Matrix Size:',matrix_notation.size)
print('Matrix Shape:',matrix_notation.shape)
print("Accessing element A[1,1]:",matrix_notation[1,1])


Vector Notation v:
 [ 5 -1  3]
Type: <class 'numpy.ndarray'>
Vector Size: 3
Vector Shape: (3,)
Accessing Element v[1]: -1

Marix Notaion: [[45 65]
 [22 33]]
Type: <class 'numpy.ndarray'>
Matrix Size: 4
Matrix Shape: (2, 2)
Accessing element A[1,1]: 33
